window.SAT_EXTRA_LESSON_PAIRS = {
  lesson5: {
    title: "Lesson 5",
    description: "Inequalities, rates, cost, and practical word-problem vocabulary",
    unlockAt: "2026-05-11T20:00:00+05:00",
    pairs: [
      ["greater than", "dan ko‘p"],
      ["less than", "dan kam"],
      ["salary", "maosh"],
      ["triple", "3 marta katta"],
      ["double", "2 marta katta"],
      ["twice", "ikki marta"],
      ["side", "tomon"],
      ["fraction", "kasr"],
      ["numerator", "surat"],
      ["denominator", "maxraj"],
      ["whose", "o‘zining"],
      ["undefined", "aniqlanmagan"],
      ["direct", "to‘g‘ri"],
      ["inverse", "teskari"],
      ["slope", "burchak koeffisiyenti"],
      ["pass", "kesib o‘tmoq"],
      ["origin", "koordinata boshi"],
      ["population", "o‘zgarish, ko‘payish"],
      ["relationship", "bog‘lanish"],
      ["object", "narsa, buyum"],
      ["distance", "masofa"],
      ["measure", "o‘lchov"],
      ["speed", "tezlik"],
      ["car", "mashina"],
      ["travel", "sayohat qilmoq"],
      ["stopping distance", "to‘xtash masofasi"],
      ["light source", "svetafor"],
      ["wall", "devor"],
      ["pairs", "juftliklar"],
      ["should", "kerak"],
      ["currently", "hozirda"],
      ["goal", "maqsad"],
      ["at least", "kamida"],
      ["want", "xohlamoq"],
      ["average", "o‘rtacha"],
      ["produce", "ishlab chiqarmoq"],
      ["product", "mahsulot"],
      ["combine", "aralashtirmoq"],
      ["with", "bilan"],
      ["cost", "narx"],
      ["purchase", "xarid qilmoq"],
      ["store", "do‘kon"],
      ["initial", "dastlabki"],
      ["other", "boshqa"],
      ["charge", "narx qo‘ymoq"],
      ["fee", "xizmat haqi"],
      ["last", "so‘nggi"],
      ["amount", "miqdor"],
      ["total", "umumiy"],
      ["pay", "to‘lamoq"]
    ]
  },
  lesson6: {
    title: "Lesson 6",
    description: "Geometry, trigonometry, comparison, and measurement vocabulary",
    unlockAt: "2026-05-12T20:00:00+05:00",
    pairs: [
      ["speed", "tezlik"],
      ["its", "o‘zining"],
      ["square", "kvadratga oshirmoq"],
      ["ratio", "nisbat"],
      ["close to", "yaqin"],
      ["respectively", "mos ravishda"],
      ["height", "balandlik"],
      ["assume", "faraz qilmoq"],
      ["far", "uzoq"],
      ["late", "kech"],
      ["little", "oz"],
      ["many", "ko‘p"],
      ["entire", "to‘liq, butun"],
      ["average", "o‘rtacha"],
      ["like term", "o‘xshash hadlar"],
      ["identity", "ayniyat"],
      ["circumference", "aylana uzunligi"],
      ["arc", "yoy"],
      ["measure", "o‘lchov"],
      ["degree", "daraja"],
      ["unit circle", "birlik aylana"],
      ["familiar", "o‘xshash"],
      ["triangle", "uchburchak"],
      ["center", "markaz"],
      ["angle", "burchak"],
      ["isosceles triangle", "teng yonli uchburchak"],
      ["area", "yuza"],
      ["similar", "o‘xshash"],
      ["acute angle", "o‘tkir burchak"],
      ["tall", "uzun"],
      ["weight", "og‘ir"],
      ["terminal", "yakuniy"],
      ["new", "yangi"],
      ["fast", "tez"],
      ["big", "katta"],
      ["large", "katta"],
      ["heavy", "og‘ir"],
      ["long", "uzun"],
      ["near", "yaqin"],
      ["simple", "oddiy"],
      ["small", "kichik"],
      ["old", "qari"],
      ["sine", "sinus"],
      ["cosine", "kosinus"],
      ["tangent", "tangens"],
      ["cotangent", "kotangens"],
      ["complement", "to‘ldiruvchi"],
      ["given", "berilgan"],
      ["revolution", "to‘liq bir aylanish"],
      ["effective", "samarali"]
    ]
  },
  lesson7: {
    title: "Lesson 7",
    description: "Coordinate geometry, angles, probability, and directional vocabulary",
    unlockAt: "2026-05-13T20:00:00+05:00",
    pairs: [
      ["represent", "namoyish qilmoq"],
      ["area", "yuza"],
      ["scale", "masshtab"],
      ["length", "uzunlik"],
      ["quadrant", "chorak"],
      ["line", "chiziq"],
      ["angle", "burchak"],
      ["segment", "kesma"],
      ["shadow", "soya"],
      ["similar", "o‘xshash"],
      ["ray", "nur"],
      ["isosceles triangle", "teng yonli uchburchak"],
      ["each other", "bir biri"],
      ["such that", "shu kabi, shundan"],
      ["therefore", "shuning uchun"],
      ["so", "shunday qilib, demak"],
      ["such", "shunaqa, bunaqa"],
      ["as", "kabi, sifatida"],
      ["digit", "raqam"],
      ["various", "turli xil"],
      ["probability", "ehtimollik"],
      ["mixed", "aralashtirilgan"],
      ["point", "nuqta"],
      ["direction", "yo‘nalish"],
      ["part", "qism"],
      ["bisector", "bissektrisa"],
      ["midpoint", "markaziy nuqta"],
      ["measure", "o‘lchov"],
      ["acute angle", "o‘tkir burchak"],
      ["right angle", "to‘g‘ri burchak"],
      ["obtuse angle", "o‘tmas burchak"],
      ["straight angle", "yoyiq burchak"],
      ["angle bisector", "burchak bissektrisa"],
      ["congruent", "teng"],
      ["supplementary angle", "qo‘shni burchak"],
      ["complementary angle", "to‘ldiruvchi burchak"],
      ["corresponding angle", "mos burchak"],
      ["interior angle", "ichki burchak"],
      ["exterior angle", "tashqi burchak"],
      ["plane", "tekislik"],
      ["opposite", "qarama-qarshi"],
      ["shortest", "eng qisqa"],
      ["the smallest", "eng kichik"],
      ["tenth of a unit", "o‘ndan bir"],
      ["same", "bir xil"],
      ["ratio", "nisbat"],
      ["south", "janub"],
      ["east", "sharq"],
      ["north", "shimol"],
      ["west", "g‘arb"]
    ]
  },
  lesson8: {
    title: "Lesson 8",
    description: "Polygon, triangle, circle, and similarity vocabulary",
    unlockAt: "2026-05-14T20:00:00+05:00",
    pairs: [
      ["area", "yuza"],
      ["height", "balandlik"],
      ["altitude", "balandlik"],
      ["opposite sides", "qarama-qarshi tomonlar"],
      ["rectangle", "to‘rtburchak"],
      ["square", "kvadrat"],
      ["trapezoid", "trapetsiya"],
      ["isosceles triangle", "teng yonli uchburchak"],
      ["equilateral triangle", "teng tomonli uchburchak"],
      ["scalene triangle", "turli tomonli uchburchak"],
      ["altitude of a triangle", "uchburchakning balandligi"],
      ["median", "mediana"],
      ["circumference", "aylana uzunligi"],
      ["straight angle", "yoyiq burchak"],
      ["polygon", "ko‘pburchak"],
      ["regular polygon", "muntazam ko‘pburchak"],
      ["irregular polygon", "muntazam bo‘lmagan ko‘pburchak"],
      ["quadrilateral", "to‘rtburchak"],
      ["pentagon", "beshburchak"],
      ["hexagon", "olti burchak"],
      ["octagon", "sakkiz burchak"],
      ["diagonal", "diagonal"],
      ["circle", "aylana"],
      ["side", "tomon"],
      ["length", "uzunlik"],
      ["width", "kenglik"],
      ["rhombus", "romb"],
      ["base of a trapezoid", "trapetsiyaning asosi"],
      ["legs of a trapezoid", "trapetsiyaning yon tomonlari"],
      ["midsegment", "o‘rta segment"],
      ["inscribed", "ichki chizilgan"],
      ["tangent", "urinma"],
      ["radius of a regular polygon", "muntazam ko‘pburchakning radiusi"],
      ["central angle", "markaziy burchak"],
      ["intersection", "kesishma"],
      ["symmetry", "simmetriya"],
      ["translation", "ko‘chirish"],
      ["transformation", "o‘zgarish"],
      ["ratio", "nisbat"],
      ["proportion", "proporsiya"],
      ["similarity", "o‘xshashlik"],
      ["scale factor", "o‘xshashlik koeffitsiyenti"],
      ["that", "shu"],
      ["which", "qaysi"],
      ["who", "kim"],
      ["where", "qayerda"],
      ["whose", "kimning"],
      ["ratio", "nisbat"],
      ["cross multiply", "chayqaltirib ko‘paytirish"],
      ["comparison", "taqqoslash"]
    ]
  },
  lesson9: {
    title: "Lesson 9",
    description: "Circle geometry, construction, and transformation vocabulary",
    unlockAt: "2026-05-15T20:00:00+05:00",
    pairs: [
      ["arc", "yoy"],
      ["radius", "radius"],
      ["diameter", "diametr"],
      ["central angle", "markaziy burchak"],
      ["minor arc", "kichik yoy"],
      ["major arc", "katta yoy"],
      ["semicircle", "yarim doira"],
      ["sector", "sektor"],
      ["congruent arcs", "teng yoylar"],
      ["point of tangency", "urinish nuqtasi"],
      ["perpendicular", "perpendikulyar"],
      ["parallel", "parallel"],
      ["intersection", "kesishish"],
      ["radian", "radian"],
      ["degree", "daraja"],
      ["circumference", "aylana uzunligi"],
      ["formula", "formula"],
      ["segment", "kesma"],
      ["chord", "vatar"],
      ["circular", "doirasimon"],
      ["distance", "masofa"],
      ["measure", "o‘lchov"],
      ["unit", "birlik"],
      ["calculation", "hisoblash"],
      ["inscribed angle", "aylanaga ichiga chizilgan burchak"],
      ["substitution", "o‘rnini bosish"],
      ["property", "xususiyat"],
      ["interior", "ichki"],
      ["exterior", "tashqi"],
      ["endpoint", "oxirgi nuqta"],
      ["length", "uzunlik"],
      ["equidistant", "bir xil masofada joylashgan"],
      ["midpoint", "o‘rtancha nuqta"],
      ["origin", "boshlang‘ich nuqta"],
      ["symmetry", "simmetriya"],
      ["given", "berilgan"],
      ["divided", "bo‘lingan"],
      ["inscribed", "ichiga chizilgan"],
      ["drawn", "chizilgan"],
      ["constructed", "qurilgan"],
      ["defined", "aniqlangan"],
      ["measured", "o‘lchangan"],
      ["calculated", "hisoblangan"],
      ["determined", "belgilangan"],
      ["marked", "belgilangan"],
      ["translated", "ko‘chirilgan"],
      ["shifted", "siljitilgan"],
      ["bisected", "ikkiga bo‘lingan"],
      ["intersected", "kesishgan"],
      ["applied", "qo‘llangan"]
    ]
  },
  lesson10: {
    title: "Lesson 10",
    description: "Modal verbs, 3D solids, volume, and surface vocabulary",
    unlockAt: "2026-05-16T20:00:00+05:00",
    pairs: [
      ["can / could", "qila olmoq"],
      ["may / might", "bo‘lishi mumkin"],
      ["must", "bo‘lishi shart"],
      ["will / would", "bo‘ladi / bo‘lardi"],
      ["ought to", "kerak"],
      ["need", "kerak"],
      ["have to", "kerak"],
      ["from", "dan"],
      ["to", "ga"],
      ["volume", "hajm"],
      ["lateral surface area", "yon sirt maydoni"],
      ["total surface area", "umumiy sirt maydoni"],
      ["base area", "asos yuzi"],
      ["edge", "qirra"],
      ["face", "yuz"],
      ["prism", "prizma"],
      ["cube", "kub"],
      ["figure", "shakl"],
      ["rectangular prism", "to‘rtburchak prizma"],
      ["right prism", "to‘g‘ri prizma"],
      ["oblique prism", "og‘ma prizma"],
      ["cross section", "kesim"],
      ["parallel faces", "parallel yuzlar"],
      ["lateral edge", "yon qirra"],
      ["cylinder", "silindr"],
      ["sphere", "shar"],
      ["hemisphere", "yarim shar"],
      ["pyramid", "piramida"],
      ["cone", "konus"],
      ["square pyramid", "to‘rtburchakli piramida"],
      ["triangular pyramid", "uchburchakli piramida"],
      ["base of a pyramid", "piramidaning asosi"],
      ["coordinate", "koordinata"],
      ["midpoint", "o‘rta nuqta"],
      ["coordinate plane", "koordinata tekisligi"],
      ["density", "zichlik"],
      ["painted", "bo‘yalgan"],
      ["entire", "to‘liq"],
      ["piece", "qism"],
      ["wood", "yog‘och"],
      ["top", "yuqori qismi"],
      ["bottom", "pastki qismi"],
      ["empty", "bo‘sh"],
      ["manufacturing", "ishlab chiqaruvchi"],
      ["produce", "ishlab chiqarmoq"],
      ["part", "qism"],
      ["enough", "yetarli"],
      ["cover", "qoplamoq"],
      ["exactly", "aniq"],
      ["tangency", "urinish"]
    ]
  },
  lesson11: {
    title: "Lesson 11",
    description: "Linear equations, slope, graphing, and quantifier vocabulary",
    unlockAt: "2026-05-17T20:00:00+05:00",
    pairs: [
      ["solving", "yechish"],
      ["linear", "chiziqli"],
      ["some", "bir nechta, bir qancha"],
      ["any", "istalgan"],
      ["both", "ikkisixam"],
      ["either", "yo unisi … yo bunisi"],
      ["neither", "unisi ham emas … bunisi ham emas"],
      ["identity", "ayniyat"],
      ["unspecified", "noma’lum"],
      ["consecutive", "ketma-ket"],
      ["find", "topmoq"],
      ["way", "usul"],
      ["properties of equality", "tenglik xossalari"],
      ["often", "odatda"],
      ["slope of line", "chiziqning burchak koeffitsiyenti"],
      ["go up and to the right", "yuqoriga va o‘ngga qarab harakatlanmoq"],
      ["go down and to the right", "pastga va o‘ngga qarab harakatlanmoq"],
      ["decrease", "kamaymoq"],
      ["reduce", "kamaytirmoq"],
      ["quotient", "bo‘linma"],
      ["three quarters", "4 dan 3"],
      ["total", "umumiy"],
      ["attend", "qabul qilinmoq"],
      ["amount", "miqdor"],
      ["per cup", "har bir piyola"],
      ["make", "hosil qilmoq"],
      ["cost", "narx"],
      ["a pair", "bir juft"],
      ["same", "bir xil"],
      ["exceed", "oshmoq, ortiq bo‘lmoq"],
      ["plotted points", "grafikda berilgan nuqta"],
      ["also", "shuningdek"],
      ["through", "orqali, ichidan"],
      ["last week", "o‘tgan hafta"],
      ["during", "davomida"],
      ["relationship", "bog‘lanish"],
      ["between", "o‘rtasidagi"],
      ["pass through", "orqali kesib o‘tmoq"],
      ["speed", "tezlik"],
      ["lie", "yotmoq"],
      ["charge", "narx belgilamoq"],
      ["initial", "dastlabki"],
      ["list", "ro‘yxat"],
      ["satisfy", "qanoatlantirmoq"],
      ["infinitely", "cheksiz"],
      ["origin", "koordinata boshi"],
      ["describe", "tasvirlamoq"],
      ["select", "tanlamoq"],
      ["none of", "hech qaysi"],
      ["other", "boshqa"]
    ]
  }
};